title: Bruin Underwater Robotics @ UCLA

include:
  - _pages

permalink: pretty
plugins:
  - jekyll-feed
  - jekyll-sitemap

defaults:
  - scope:
      path: "_pages"
      type: "pages"
    values:
      permalink: /:basename/